
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhmghmplsfdtqkkizpud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1obWdobXBsc2ZkdHFra2l6cHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjEzODksImV4cCI6MjA2MDA5NzM4OX0.91mMgvR1yS0DPeoA3wvg4_cD1XZ2YFDidGXM75qrvSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Make sure localStorage is only accessed in browser context
const storage = typeof window !== 'undefined' ? localStorage : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: storage
  }
});
